# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-19 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_historicalitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='properties',
        ),
        migrations.AddField(
            model_name='variant',
            name='cloth',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='size',
            field=models.CharField(blank=True, choices=[(None, 'Please Select'), ('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE'), ('XL', 'EXTRA LARGE')], default=None, max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
