# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-24 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20180224_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='item',
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='Variant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logs.Variant'),
        ),
        migrations.AddField(
            model_name='item',
            name='Variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logs.Variant'),
        ),
    ]
