# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-24 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_auto_20180224_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalitem',
            old_name='Variant',
            new_name='variant',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Variant',
            new_name='variant',
        ),
    ]
