# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-24 19:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0006_auto_20180224_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVariant',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[(None, 'Please Select'), ('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE'), ('XL', 'EXTRA LARGE')], default=None, max_length=3, null=True)),
                ('cloth', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50)),
                ('selling_price', models.IntegerField()),
                ('cost_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical variant',
            },
        ),
    ]
